name: Create release
run-name: ${{ github.actor }}的自动发布
on:
  pull_request:
    # 当 PR 被关闭时触发 
    # 详见 https://docs.github.com/zh/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request
    types: 
      - closed
    branches:
      - main

jobs:
  mergedNrelease:
    # 仅当 PR 被合并，且是 dev 分支合并至 main 分支时执行
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'dev'
    runs-on: ubuntu-latest
    steps:
      # 作用之一——将工作目录设置为当前仓库根目录
      - name: Checkout code
        uses: actions/checkout@v4

      # 读取版本号和更新日志 因为 runs on ubuntu 所以注意保持要读取文件行尾换行符为 LF
      - name: Read version and changelog from CHANGELOG.MD
        id: get_ver_cl
        run: |
          LATEST_VERSION=$(awk '/^## \[/{print $2; exit}' CHANGELOG.MD | tr -d '[]')
          CHANGELOG=$(awk -v version="${LATEST_VERSION}" '/^## \[/{if ($2 == "["version"]") {flag=1;next} else {flag = 0;}} flag==1 {print;}' CHANGELOG.MD)
          echo "LATEST_VERSION=${LATEST_VERSION}" >> $GITHUB_OUTPUT
          printf "CHANGELOG<<EOF\n%s\nEOF\n" "$CHANGELOG" >> $GITHUB_OUTPUT
      
      # 在工作目录中创建 zip 包
      - name: Create ZIP
        run: zip -r KSP_Chinese_Patches_${{ steps.get_ver_cl.outputs.LATEST_VERSION }}.zip GameData

      # 文件准备
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: KSP_Chinese_Patches_${{ steps.get_ver_cl.outputs.LATEST_VERSION }}.zip
          path: KSP_Chinese_Patches_${{ steps.get_ver_cl.outputs.LATEST_VERSION }}.zip
      
      # 创建发布页面 详见 https://github.com/marketplace/actions/gh-release
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_ver_cl.outputs.LATEST_VERSION }}
          name:  KSP Mod 中文翻译补丁合集 | KSP Chinese Patches v${{ steps.get_ver_cl.outputs.LATEST_VERSION }}
          body: |
            该发布由 GitHub 自动构建，当前项目版本：${{ steps.get_ver_cl.outputs.LATEST_VERSION }}
            所属 PR：${{ github.event.pull_request.html_url }}
            ## 更新内容：
            ${{ steps.get_ver_cl.outputs.CHANGELOG }}
          files: KSP_Chinese_Patches_${{ steps.get_ver_cl.outputs.LATEST_VERSION }}.zip
        env:
          # 注意去设置 Workflow permissions 为 Read and write permissions 否则会失败 或另新建一个专用的 token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
